Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 512
      Handler: helloworld.App
      CodeUri: /home/walter/Área de Trabalho/Projetos/localstack/aws-pub-sub-main/HelloWordWalter/HelloWorldFunction
      Runtime: java17
      Architectures:
        - x86_64